lilypad/_configure.py, lilypad/_opentelemetry/_opentelemetry_outlines/__init__.py, lilypad/_opentelemetry/_opentelemetry_outlines/patch.py, lilypad/_opentelemetry/_opentelemetry_outlines/utils.py, lilypad/_utils/__init__.py, lilypad/_utils/call_safely.py, lilypad/generations.py, tests/_utils/test_call_safely.py, tests/test_response_model.py, uv.lock
=> fix: ensure generations always call user code and never crash on lilypad errors

.vscode/settings.json, client/src/components/ArgsCards.tsx, client/src/components/GenerationSpans.tsx, client/src/components/SelectVerisonForm.tsx, client/src/routeTree.gen.ts, client/src/routes/_auth.projects.$projectUuid.generations.$generationName.tsx, client/src/routes/_auth.projects.$projectUuid.generations.index.tsx, client/src/routes/_auth.projects.$projectUuid.prompts.index.tsx, client/src/utils/generations.ts, client/src/utils/prompts.ts, lilypad/server/api/v0/generations_api.py, lilypad/server/api/v0/prompts_api.py, lilypad/server/models/base_sql_model.py, lilypad/server/services/generations.py, uv.lock
Closes #60
Closes #72 
Closes #75
=> fix: generation overflowing

client/src/components/DataTable.tsx, client/src/components/TracesTable.tsx, client/src/routeTree.gen.ts, client/src/routes/_auth.projects.$projectUuid.traces.$.tsx, lilypad/_configure.py
=> feat: open details page when using a trace uuid, output trace url whe

lilypad/_opentelemetry/_opentelemetry_outlines/patch.py, lilypad/_opentelemetry/_opentelemetry_outlines/utils.py, tests/_opentelemetry/_opentelemetry_outlines/test_utils.py
Fixes: https://github.com/Mirascope/lilypad/issues/133
=> fix: outlines response message

pyproject.toml, uv.lock
Fixes: https://github.com/Mirascope/lilypad/issues/155
=> fix: fix cachetools deps

lilypad/_utils/closure.py, pyproject.toml, tests/_utils/closure/closure_test_functions/main.py, tests/_utils/closure/test_closure.py
Fixes: https://github.com/Mirascope/lilypad/issues/156
=> fix: fix nested BaseModel definitions

lilypad/_utils/closure.py, lilypad/ee/server/api/v0/datasets_api.py, lilypad/response_models.py, tests/_utils/closure/closure_test_functions/main.py, tests/_utils/closure/closure_test_functions/other.py, tests/_utils/closure/test_closure.py, tests/test_response_model.py, uv.lock
Fixes: https://github.com/Mirascope/lilypad/issues/157
=> fix: fix class attribute in top-level

client/src/components/DataTable.tsx, client/src/components/TracesTable.tsx
=> fix: broken filter and hide annotation from llm traces

lilypad/_opentelemetry/_opentelemetry_openai/utils.py, lilypad/server/_utils/spans.py, tests/_opentelemetry/_opentelemetry_openai/test_utils.py
=> fix: openai tools base model and smooshed user and system messages

client/src/routes/_auth.projects.$projectUuid.generations.$generationName.$generationUuid.$tab.tsx, client/src/utils/generations.ts, lilypad/server/api/v0/generations_api.py
=> fix: setting active on generation

client/src/components/LilypadDialog.tsx, client/src/components/Playground.tsx, client/src/components/SelectVerisonForm.tsx, client/src/components/TracesTable.tsx, client/src/ee/components/AnnotationForm.tsx, client/src/ee/components/AnnotationQueueDialog.tsx, client/src/ee/components/AnnotationsTable.tsx, client/src/routes/_auth.projects.$projectUuid.generations.$generationName.$generationUuid.$tab.tsx
=> fix: add input output when annotating directly

client/src/components/LayoutSkeleton.tsx, client/src/routes/_auth.projects.$projectUuid.generations.index.tsx, client/src/routes/_auth.tsx
=> fix: no loading state for projects

lilypad/_configure.py, lilypad/server/client.py, lilypad/server/main.py
Fixes: https://github.com/Mirascope/lilypad/issues/135
=> Fix configure log outputs

lilypad/server/api/v0/prompts_api.py
=> fix: prompts run button

lilypad/prompts.py, lilypad/server/client.py
Closes: https://github.com/Mirascope/lilypad/issues/189
=> Add prompt version method

client/src/components/APIKeysTable.tsx, client/src/components/ProjectsTable.tsx, client/src/components/TracesTable.tsx, client/src/components/ui/badge.tsx, client/src/utils/strings.tsx, lilypad/_utils/call_safely.py, lilypad/exceptions.py, lilypad/generations.py, lilypad/server/client.py, tests/_utils/test_call_safely.py, tests/server/test_client.py, uv.lock
=> feat: only call safely for lilypad exceptions, ui updates for errors

lilypad/_configure.py, lilypad/generations.py
Fixes: https://github.com/Mirascope/lilypad/issues/214
=> fix: fix nested span oder

client/src/components/APIKeysTable.tsx
=> fix: wrong project id

client/src/components/AppSidebar.tsx, client/src/ee/components/AnnotationForm.tsx
=> fix: navigate to section root instead of traces

lilypad/_utils/closure.py, tests/_utils/closure/closure_test_functions/main.py, tests/_utils/closure/test_closure.py, uv.lock
Fixes: https://github.com/Mirascope/lilypad/issues/200
=> fix: fix closure with class method

client/src/components/AppSidebar.tsx, client/src/components/CostAndTokensChart.tsx, client/src/components/MetricsCharts.tsx, client/src/routeTree.gen.ts, client/src/routes/_auth.projects.$projectUuid.index.tsx, client/src/routes/_auth.projects.index.tsx, client/src/types/types.ts, client/src/utils/generations.ts, client/src/utils/spans.ts, lilypad/server/api/v0/spans_api.py, lilypad/server/services/spans.py, uv.lock
Clicking on the lilypad frog will navigate to project dashboard.
=> feat: added projects dashboard

lilypad/_configure.py, lilypad/_opentelemetry/__init__.py, lilypad/_opentelemetry/_opentelemetry_azure/__init__.py, lilypad/_opentelemetry/_opentelemetry_azure/patch.py, lilypad/_opentelemetry/_opentelemetry_azure/utils.py, lilypad/_opentelemetry/_opentelemetry_bedrock/__init__.py, lilypad/server/_utils/spans.py, lilypad/server/api/v0/traces_api.py, pyproject.toml, tests/_opentelemetry/_opentelemetry_azure/test_patch.py, tests/_opentelemetry/_opentelemetry_azure/test_utils.py, tests/_utils/closure/test_closure.py, tests/server/_utils/test_spans.py, uv.lock
Closes: https://github.com/Mirascope/lilypad/issues/293
=> feat: Support Azure SDK

client/src/components/DataTable.tsx, client/src/components/TracesTable.tsx
* Closes #306 
* Closes #275 
* Closes #304
=> fix: broken navigation on spans table

client/src/ee/components/PlaygroundContainer.tsx, client/src/ee/hooks/use-playground.tsx, lilypad/server/api/v0/external_api_keys_api.py
Fixes: https://github.com/Mirascope/lilypad/issues/365
=> fix: show playground result

lilypad/ee/server/api/v0/annotations_api.py, lilypad/ee/server/generations/annotate_trace.py, pyproject.toml, uv.lock
Closes: https://github.com/Mirascope/lilypad/issues/361
=> Cleanup optional deps

lilypad/server/api/v0/traces_api.py
Fixes: https://github.com/Mirascope/lilypad/issues/343
=> Fix google genai cost

client/src/components/KeysSettings.tsx, client/src/ee/components/Playground.tsx, client/src/ee/components/PlaygroundContainer.tsx, client/src/ee/hooks/use-playground.tsx, client/src/ee/utils/functions.ts, client/src/routes/_auth/projects/$projectUuid/playground/$functionName/compare.$firstFunctionUuid.$secondFunctionUuid.tsx, client/src/types/types.ts, lilypad/ee/server/api/v0/functions_api.py, lilypad/server/schemas/external_api_keys.py, lilypad/server/schemas/functions.py, lilypad/server/services/spans.py
Fixes: https://github.com/Mirascope/lilypad/issues/369 https://github.com/Mirascope/lilypad/issues/368
=> fix: improve playground response

client/src/components/DataTable.tsx
=> fix: scrolling issue

client/Dockerfile.dev, client/src/components/AppSidebar.tsx, client/src/components/LilypadPanel.tsx, client/src/utils/panel-utils.tsx, lilypad/server/schemas/span_more_details.py
Related to https://github.com/Mirascope/lilypad-sdk-python/pull/101
=> fix: traces rendering

lilypad/server/schemas/span_more_details.py, lilypad/server/services/opensearch.py
=> fix: missing system message

client/src/components/JsonView.tsx, client/src/components/LilypadMarkdown.tsx, client/src/components/traces/SpanFullDetail.tsx, client/src/components/ui/scroll-area.tsx, client/src/ee/components/Editor.tsx, client/src/routes/_auth/projects/$projectUuid/annotations/$.tsx, client/src/routes/_auth/projects/$projectUuid/traces/detail.$spanUuid.tsx, client/src/utils/panel-utils.tsx
=> fix: layout issues and some inconsistent layouts

.gitguardian.yml
I added the config file for GitGuardian.
https://docs.gitguardian.com/ggshield-docs/configuration#configuration-files
=> chore: add GitGuardian configuration file to manage scanning behavior

app/client/src/components/DataTable.tsx, app/client/src/routes/_auth/projects/$projectUuid/traces.$.tsx
=> fix: undo some real-time-updates issues preventing clicking on span details

app/lilypad/server/services/data_retention_service.py, app/lilypad/server/services/opensearch.py, app/lilypad/server/settings.py, app/tests/server/services/test_billing_service.py, app/tests/server/services/test_data_retention_service.py, app/tests/server/services/test_opensearch.py
=> feat: Implement OpenSearch deletion in data retention workflow

sdks/python/src/lilypad/_opentelemetry/_opentelemetry_openai/__init__.py, sdks/python/tests/_opentelemetry/_opentelemetry_openai/test_instrumentor.py
Fixes: https://github.com/Mirascope/lilypad/issues/589
=> feat: enhance OpenAI instrumentation with version compatibility

CLAUDE.md
Updated CLAUDE.md with additional development guidelines, clarified architecture details, and added information about testing requirements and deployment processes.
- Added guidelines about not creating unnecessary files or documentation
- Added new development commands: `codespell` and `lint:ci`
- Enhanced architecture description with reference to detailed documentation
- Clarified tooling details including pre-commit hooks and test coverage requirements
- Added more specific information about staging environment and PR deployments
- Included details about database technology (ParadeDB pg_search extensions)
- Added notes about pre-commit hooks, test coverage requirements, and PR preview deployments
Review the updated CLAUDE.md file to ensure the new information is accurate and …
=> docs: Update CLAUDE.md with enhanced development guidelines
